#ifndef NEIGHBOREVENTSTATE_H_INCLUDED
#define NEIGHBOREVENTSTATE_H_INCLUDED

enum Nbr_Event{
    NBR_EVT_HELLORECV = 0,
    NBR_EVT_START,
    NBR_EVT_2WAYRECV,
    NBR_EVT_NEGOTIATIONDONE,
    NBR_EVT_EXCHANGEDONE,
    NBR_EVT_BADLSREQ,
    NBR_EVT_LOADINGDONE,
    NBR_EVT_ADJOK,
    NBR_EVT_SEQNUMMISMATCH,
    NBR_EVT_1WAY,
    NBR_EVT_KILLNBR,
    NBR_EVT_INACTTIMER,
    NBR_EVT_LLDOWN
};

enum Nbr_State{
    NBR_ST_DOWN = 0,
    NBR_ST_ATTEMPT,
    NBR_ST_INIT,
    NBR_ST_2WAY,
    NBR_ST_EXSTART,
    NBR_ST_EXCHANGE,
    NBR_ST_LOADING,
    NBR_ST_FULL
};

#endif // NEIGHBOREVENTSTATE_H_INCLUDED
